# spring.application.name=board

spring:
  application:
    name: board # 프로젝트 이름
  datasource: # 데이터베이스 접속정보
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: green502

mybatis: # Mybatis 세팅
  mapper-locations: mappers/**/*.xml # xml파일 위치 /  mappers폴더 아래에/어떤 폴더가있어도 상관없고 / .xml로 끝나는 모든 파일